<div class="navbar"><h1 class="txtC">Loading view</h1></div>
<div class="line"></div>
<div class="txtC">
  <a id="toggle-loading" class="button" href="#">Toggle loading view</a>
  <a id="toggle-loading-custom" class="button" href="#">Toggle loading view w/ another text</a>
</div>


<script type="text/javascript">
  $("#toggle-loading").click(function(e) {
    e.preventDefault();
    loading("Loading...").toggle();
  });
  
  $("#toggle-loading-custom").click(function(e) {
    e.preventDefault();
    loading("Please wait...").toggle();
  });
</script>