<div class="navbar"><h1 class="txtC">Button Bar</h1></div>
<div class="flex"></div>
<div style="margin: 0 100px;">
  <div class="buttonbar">
    <a href="#" class="button" data="{ icons: { primary: 'ui-icon-plus' }, text: false }">Add something</a>
    <a href="#" class="button" data="{ icons: { primary: 'ui-icon-minus' }, text: false }">Delete something</a>
  </div>
</div>
<div class="flex"></div>