<div class="flex"></div>
<div class="txtC">
  <input type="checkbox" id="check" class="button" /><label for="check">Toggle</label>

  <div id="format" class="buttonset">
  	<input type="checkbox" id="check1" /><label for="check1">B</label>
  	<input type="checkbox" id="check2" /><label for="check2">I</label>
  	<input type="checkbox" id="check3" /><label for="check3">U</label>
  </div>
</div>
<div class="flex"></div>